In [1]:
import pandas as pd

sensus = {
    'tinggi': [159, 170, 183, 191, 155, 163, 180, 158, 178],
    'berat': [64, 86, 84, 80, 49, 59, 67, 54, 67], 
    'jk':  ['pria', 'pria', 'pria', 'pria', 'wanita', 'wanita', 'wanita', 'wanita', 'wanita',]}

sensus_df = pd.DataFrame(sensus)
sensus_df

,tinggi,berat,jk
0,159,64,pria
1,170,86,pria
2,183,84,pria
3,191,80,pria
4,155,49,wanita
5,163,59,wanita
6,180,67,wanita
7,158,54,wanita
8,178,67,wanita


In [2]:
import numpy as np

x_train = np.array(sensus_df[['tinggi', 'jk']])
y_train = np.array(sensus_df['berat'])

print(f'x_train:\n{x_train}\n')
print(f'y_train: {y_train}')

x_train:
[[159 'pria']
 [170 'pria']
 [183 'pria']
 [191 'pria']
 [155 'wanita']
 [163 'wanita']
 [180 'wanita']
 [158 'wanita']
 [178 'wanita']]

y_train: [64 86 84 80 49 59 67 54 67]


In [3]:
x_train_transposed = np.transpose(x_train)

print(f'x_train:\n{x_train}\n')
print(f'y_train_transposed:\n{x_train_transposed}')

x_train:
[[159 'pria']
 [170 'pria']
 [183 'pria']
 [191 'pria']
 [155 'wanita']
 [163 'wanita']
 [180 'wanita']
 [158 'wanita']
 [178 'wanita']]

y_train_transposed:
[[159 170 183 191 155 163 180 158 178]
 ['pria' 'pria' 'pria' 'pria' 'wanita' 'wanita' 'wanita' 'wanita'
  'wanita']]


In [5]:
from sklearn.preprocessing import LabelBinarizer

lb = LabelBinarizer()
jk_binarised = lb.fit_transform(x_train_transposed[1])

print(f'jk: {x_train_transposed[1]}\n')
print(f'jk_binarised:\n{jk_binarised}')

jk: ['pria' 'pria' 'pria' 'pria' 'wanita' 'wanita' 'wanita' 'wanita' 'wanita']

jk_binarised:
[[0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]]


In [6]:
jk_binarised = jk_binarised.flatten()
jk_binarised

array([0, 0, 0, 0, 1, 1, 1, 1, 1])

In [7]:
x_train_transposed[1] = jk_binarised
x_train = x_train_transposed.transpose()

print(f'y_train_transposed:\n{x_train_transposed}')
print(f'x_train:\n{x_train}\n')

y_train_transposed:
[[159 170 183 191 155 163 180 158 178]
 [0 0 0 0 1 1 1 1 1]]
x_train:
[[159 0]
 [170 0]
 [183 0]
 [191 0]
 [155 1]
 [163 1]
 [180 1]
 [158 1]
 [178 1]]

